[phases.setup]
nixPkgs = ["python310", "python310Packages.pip", "python310Packages.virtualenv"]

[phases.install]
cmds = [
  "python -m venv /opt/venv",
  ". /opt/venv/bin/activate && cd backend && pip install --upgrade pip",
  ". /opt/venv/bin/activate && cd backend && pip install -r requirements.txt"
]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = ". /opt/venv/bin/activate && cd backend && gunicorn main:app --bind 0.0.0.0:$PORT"

